### ISSUE TITLE
Android app crash

### ISSUE THREAD

**Issue by LukhiKartik** [square/in-app-payments-react-native-plugin#137]

**Comment by LukhiKartik** [comment]
https://user-images.githubusercontent.com/43737760/129512814-34e93d53-f235-404b-b11d-dc087cf665b2.MP4

**Comment by LukhiKartik** [comment]
@StephenJosey I was facing android build issue but i refer this issue https://github.com/square/in-app-payments-react-native-plugin/issues/62 and added below code into build.gradle file and i can create android build successfully. Also i have tried this same app and it works fine for me without any change in build.gradle file.--> https://github.com/square/in-app-payments-react-native-plugin/tree/master/react-native-in-app-payments-quickstart. 
The only difference between sample app build and my build is below code only.

configurations {
implementation {
exclude group: 'com.nds.threeds', module: 'threedssdk-release'
}
}

**Comment by jguze** [comment]
@LukhiKartik Thanks for reporting this issue! Do you mind answering some questions to help me better understand the issue?.

1. Do you have a stacktrace of the crash you're seeing?
2. Does this happen in both Debug and Release mode?
3. Are you minifying or obfuscating your code during the build?

Also, to clarify, are you having the same crashing problem when using the [sample app](https://github.com/square/in-app-payments-react-native-plugin/tree/master/react-native-in-app-payments-quickstart)?

**Comment by LukhiKartik** [comment]
@jguze 

1) Stack trace

021-08-12 23:42:04.461 29318-29318/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: events.noq.apps, PID: 29318
    java.lang.AssertionError: Missing field in o.n

Caused by: java.lang.NoSuchFieldException: ZZ
        at java.lang.Class.getField(Class.java:1604)
        at g.i.f.t$l.<init>(Unknown Source:34)
        at g.i.f.t$c.a(Unknown Source:160) 
        at g.i.f.s.a(Unknown Source:76) 
        at g.i.f.c$a.a(Unknown Source:45) 
        at g.i.f.c$a.a(Unknown Source:159) 
        at g.i.f.s.a(Unknown Source:76) 
        at g.i.f.c$a.a(Unknown Source:45) 
        at g.i.f.c$a.a(Unknown Source:159) 
        at g.i.f.s.a(Unknown Source:76) 
        at g.i.f.c$a.a(Unknown Source:45) 
        at g.i.f.c$a.a(Unknown Source:159) 
        at g.i.f.s.a(Unknown Source:76) 
        at g.i.f.s.a(Unknown Source:1) 
        at l.x.a.a.a(Unknown Source:6) 
        at l.s.a(Unknown Source:40) 
        at l.s.a(Unknown Source:1) 
        at l.q$a.a(Unknown Source:1487) 
        at l.q$a.a(Unknown Source:11) 
        at l.q$a.a(Unknown Source:81) 
        at l.q.a(Unknown Source:5) 
        at l.t.a(Unknown Source:0) 
        at l.s.a(Unknown Source:24) 
        at l.s$a.invoke(Unknown Source:32) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006) 
        at $Proxy14.a(Unknown Source) 
        at sqip.internal.verification.m$a.a(Unknown Source:56) 
        at sqip.internal.verification.c.d(Unknown Source:19) 
        at sqip.internal.verification.c.a(Unknown Source:73) 
        at sqip.internal.verification.BuyerVerificationActivity.onCreate(Unknown Source:53) 
        at android.app.Activity.performCreate(Activity.java:7893) 
        at android.app.Activity.performCreate(Activity.java:7880) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7562) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
2021-08-12 23:42:04.541 1851-2260/? E/InputDispatcher: channel 'c3ba144 events.noq.apps/sqip.internal.CardEntryActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2021-08-12 23:42:04.541 1851-2260/? E/InputDispatcher: channel 'dde8055 events.noq.apps/events.noq.apps.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

2) Does this happen in both Debug and Release mode?
 - In local(emulator) is working but in APK its get crash
 
3) Are you minifying or obfuscating your code during the build?
- no

4) Also, to clarify, are you having the same crashing problem when using the sample app?
 - No I don't have any issue or crash in sample app, Sample app is working fine for me.

**Comment by jguze** [comment]
Thanks @LukhiKartik. A few more questions:

1. Do you know what version of the IAP SDK you're actually using? If you haven't reconfigured it, I assume it's 1.4.0.
2. I see some sort of minification seems to exist in the stacktrace. Can you share the build.gradle file for your app, if possible?

**Comment by fka3** [comment]
So, I agree field `ZZ` and the function calls e.g. ` g.i.f.t$l.(Unknown Source:34)` definitely smell obfuscated!  The default compiler (R8) and proguard can both do this, and depending on your configuration they might be on by default.  https://developer.android.com/studio/build/shrink-code#obfuscate can explain more, but the long and short is that the stack trace here _is_ obfuscated, and that without something like _retrace_ and the mapping from your build it's going to be hard to figure out what happened... but probably what happened is "obfuscation made the proxy object look for field ZZ, the newly-obfuscated name, rather than whatever the real field name is."

If you don't have retrace or the mapping, you might add a stanza like this to your `build.gradle` file:

```
android {
    ...
    buildTypes {
       release {
          // Deactivate R8.
          minifyEnabled false
       }
    }
}
```

I _think_ there is a directive specific to obfuscation, but let's start with that one to turn everything off and see what it does first.

**Comment by fka3** [comment]
That it works in the emulator but not on a hardware device (I assume that's what "in APK" means?) is interesting, but doesn't change my suggestion... however, for when we get there, which hardware device is it?  Have you tried others, especially others from different vendors?

**Comment by vatsal-gadhiya-searce** [comment]
> Thanks @LukhiKartik. A few more questions:
> 1. Do you know what version of the IAP SDK you're actually using? If you haven't reconfigured it, I assume it's 1.4.0.
      It's by default 1.4.0.
> 2. I see some sort of minification seems to exist in the stacktrace. Can you share the build.gradle file for your app, if possible?

```// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        playServicesVersion = "17.0.0"
        androidMapsUtilsVersion="2.1.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.4")
        classpath 'com.google.gms:google-services:4.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by LukhiKartik** [comment]
@jguze 

app/build.gradle

apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js",
    enableHermes: true,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = true

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "events.noq.apps"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 34
        versionName "1.8.3"
        multiDexEnabled true
        resConfigs "en"
        missingDimensionStrategy 'react-native-camera', 'general'
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('NOQCUSTOMER_RELEASE_STORE_FILE')) {
                storeFile file(NOQCUSTOMER_RELEASE_STORE_FILE)
                storePassword NOQCUSTOMER_RELEASE_STORE_PASSWORD
                keyAlias NOQCUSTOMER_RELEASE_KEY_ALIAS
                keyPassword NOQCUSTOMER_RELEASE_KEY_PASSWORD
            }
        }
    }
    buildTypes {
//        debug {
//            signingConfig signingConfigs.debug
//        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.release
            shrinkResources false
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}
// apply plugin: 'com.google.gms.google-services'
dependencies {
    implementation project(':react-native-square-in-app-payments')
    implementation project(':react-native-permissions')
    implementation project(':react-native-camera')
    implementation project(':react-native-vector-icons')
    // WORKAROUND for com.google.gms:google-services:4.2.0: https://github.com/invertase/react-native-firebase/issues/1676#issuecomment-441243419
    com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
    implementation 'com.facebook.android:facebook-login:[4,5)'
    //implementation 'com.facebook.android:facebook-android-sdk:4.34.0'
    implementation 'androidx.multidex:multidex:2.0.0'
    implementation "com.google.android.gms:play-services-base:17.0.0"
    implementation "com.google.firebase:firebase-core:16.0.9"
    implementation 'com.google.firebase:firebase-messaging:18.0.0'
    implementation 'com.google.android.gms:play-services-wallet:18.0.0'
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

configurations {
    implementation {
        exclude group: 'com.nds.threeds', module: 'threedssdk-release'
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
apply plugin: 'com.google.gms.google-services'
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)


```I have disable both fields as per your suggestion but apk size got increase(it increase about 5-6 MB)
shrinkResources false
minifyEnabled false```

Can we fix crash issue without disable shrinkResources and minifyEnabled?

**Comment by jguze** [comment]
Unfortunately, the BuyerVerification part of the Android In App Payments SDK does not currently support minification and obfuscation.

However, I've seen a similar crash before. You can try adding these proguard rules to your proguard rules file, which may fix the issue for you:
```
-keep class sqip.** { *; }
-keep class org.spongycastle.** { *; }
-keep class com.ndsthreeds.** { *; }
```
